function(lean_occt_detect_layout)
  math(EXPR _compiler_bitness "32 + 32 * (${CMAKE_SIZEOF_VOID_P} / 8)")

  if(WIN32)
    set(_os_with_bit "win${_compiler_bitness}")
  elseif(APPLE)
    set(_os_with_bit "mac${_compiler_bitness}")
  else()
    set(_os_with_bit "lin${_compiler_bitness}")
  endif()

  if(MSVC)
    set(_compiler "vc14")
  elseif(CMAKE_CXX_COMPILER_ID STREQUAL "GNU")
    set(_compiler "gcc")
  elseif(CMAKE_CXX_COMPILER_ID MATCHES "[Cc][Ll][Aa][Nn][Gg]")
    set(_compiler "clang")
  elseif(CMAKE_CXX_COMPILER_ID MATCHES "[Ii][Nn][Tt][Ee][Ll]")
    set(_compiler "icc")
  else()
    set(_compiler "${CMAKE_CXX_COMPILER_ID}")
    string(REPLACE " " "" _compiler "${_compiler}")
  endif()

  set(COMPILER_BITNESS "${_compiler_bitness}" PARENT_SCOPE)
  set(OS_WITH_BIT "${_os_with_bit}" PARENT_SCOPE)
  set(COMPILER "${_compiler}" PARENT_SCOPE)
  set(INSTALL_DIR_BIN "bin" PARENT_SCOPE)
  set(INSTALL_DIR_LIB "lib" PARENT_SCOPE)
  set(OCCT_INSTALL_BIN_LETTER "" PARENT_SCOPE)
  set(LAYOUT_IS_VCPKG OFF PARENT_SCOPE)
endfunction()

function(lean_occt_configure_output_directories)
  set(_binary_dir "${CMAKE_BINARY_DIR}/${OS_WITH_BIT}/${COMPILER}/bin")
  set(_library_dir "${CMAKE_BINARY_DIR}/${OS_WITH_BIT}/${COMPILER}/lib")

  set(CMAKE_RUNTIME_OUTPUT_DIRECTORY "${_binary_dir}" PARENT_SCOPE)
  set(CMAKE_LIBRARY_OUTPUT_DIRECTORY "${_library_dir}" PARENT_SCOPE)
  set(CMAKE_ARCHIVE_OUTPUT_DIRECTORY "${_library_dir}" PARENT_SCOPE)

  foreach(_config DEBUG RELEASE RELWITHDEBINFO MINSIZEREL)
    set("CMAKE_RUNTIME_OUTPUT_DIRECTORY_${_config}" "${_binary_dir}" PARENT_SCOPE)
    set("CMAKE_LIBRARY_OUTPUT_DIRECTORY_${_config}" "${_library_dir}" PARENT_SCOPE)
    set("CMAKE_ARCHIVE_OUTPUT_DIRECTORY_${_config}" "${_library_dir}" PARENT_SCOPE)
  endforeach()
endfunction()

function(lean_occt_collect_package_dirs the_module the_toolkit the_out_var)
  include("${CMAKE_CURRENT_SOURCE_DIR}/src/${the_module}/${the_toolkit}/PACKAGES.cmake")
  set(_package_var "OCCT_${the_toolkit}_LIST_OF_PACKAGES")
  set(_package_dirs)
  foreach(_package IN LISTS ${_package_var})
    list(APPEND _package_dirs "${CMAKE_CURRENT_SOURCE_DIR}/src/${the_module}/${the_toolkit}/${_package}")
  endforeach()
  set(${the_out_var} ${_package_dirs} PARENT_SCOPE)
endfunction()

function(lean_occt_collect_package_files the_module the_toolkit the_out_sources the_out_headers)
  include("${CMAKE_CURRENT_SOURCE_DIR}/src/${the_module}/${the_toolkit}/PACKAGES.cmake")
  set(_package_var "OCCT_${the_toolkit}_LIST_OF_PACKAGES")

  set(_sources)
  set(_headers)
    foreach(_package IN LISTS ${_package_var})
      set(_package_dir "${CMAKE_CURRENT_SOURCE_DIR}/src/${the_module}/${the_toolkit}/${_package}")
      include("${_package_dir}/FILES.cmake")
      set(_files_var "OCCT_${_package}_FILES")

      foreach(_file IN LISTS ${_files_var})
      set(_abs_file "${_package_dir}/${_file}")
      if(_file MATCHES "\\.(c|cc|cpp|cxx|mm)$")
        list(APPEND _sources "${_abs_file}")
      elseif(_file MATCHES "\\.(h|hpp|hxx|lxx|gxx|pxx|g)$")
        list(APPEND _headers "${_abs_file}")
      endif()
    endforeach()
  endforeach()

  set(${the_out_sources} ${_sources} PARENT_SCOPE)
  set(${the_out_headers} ${_headers} PARENT_SCOPE)
endfunction()

function(lean_occt_resolve_link_items the_out_var)
  set(_resolved)
  foreach(_item IN LISTS ARGN)
    if(TARGET "${_item}")
      list(APPEND _resolved "${_item}")
    elseif(_item STREQUAL "CSF_ThreadLibs")
      if(TARGET Threads::Threads)
        list(APPEND _resolved Threads::Threads)
      endif()
      if(UNIX AND NOT APPLE AND NOT EMSCRIPTEN AND NOT ANDROID)
        list(APPEND _resolved rt)
      endif()
    elseif(_item STREQUAL "CSF_TBB")
      if(OCCT_SUBSET_USE_TBB)
        list(APPEND _resolved TBB::tbb)
      endif()
    elseif(_item STREQUAL "CSF_dl")
      if(CMAKE_DL_LIBS)
        list(APPEND _resolved ${CMAKE_DL_LIBS})
      endif()
    elseif(_item STREQUAL "CSF_advapi32")
      if(WIN32)
        list(APPEND _resolved advapi32)
      endif()
    elseif(_item STREQUAL "CSF_gdi32")
      if(WIN32)
        list(APPEND _resolved gdi32)
      endif()
    elseif(_item STREQUAL "CSF_user32")
      if(WIN32)
        list(APPEND _resolved user32)
      endif()
    elseif(_item STREQUAL "CSF_psapi")
      if(WIN32)
        list(APPEND _resolved psapi)
      endif()
    elseif(_item STREQUAL "CSF_wsock32")
      if(WIN32)
        list(APPEND _resolved wsock32)
      endif()
    elseif(_item STREQUAL "CSF_androidlog")
      if(ANDROID)
        list(APPEND _resolved log)
      endif()
    elseif(_item STREQUAL "CSF_MMGR")
      continue()
    elseif(_item STREQUAL "")
      continue()
    else()
      list(APPEND _resolved "${_item}")
    endif()
  endforeach()

  if(UNIX AND NOT WIN32)
    list(APPEND _resolved m)
  endif()

  list(REMOVE_DUPLICATES _resolved)
  set(${the_out_var} ${_resolved} PARENT_SCOPE)
endfunction()

function(lean_occt_add_toolkit the_module the_toolkit)
  lean_occt_collect_package_files("${the_module}" "${the_toolkit}" _sources _headers)
  include("${CMAKE_CURRENT_SOURCE_DIR}/src/${the_module}/${the_toolkit}/EXTERNLIB.cmake")
  set(_deps_var "OCCT_${the_toolkit}_EXTERNAL_LIBS")
  lean_occt_resolve_link_items(_resolved ${${_deps_var}})

  add_library(${the_toolkit} ${_sources} ${_headers})
  target_include_directories(${the_toolkit} PUBLIC ${LEAN_OCCT_ALL_PACKAGE_DIRS})
  target_link_libraries(${the_toolkit} PUBLIC ${_resolved})
  target_compile_features(${the_toolkit} PUBLIC cxx_std_17)

  set_target_properties(${the_toolkit} PROPERTIES
    FOLDER "Modules/${the_module}"
    VERSION "${LEAN_OCCT_VERSION_COMPLETE}"
    SOVERSION "${LEAN_OCCT_VERSION_SOVERSION}"
  )
endfunction()
